"""Given a 3-digit number, you have to reverse the number.

Input Format
A single line containing a 3 digit number n.

Output Format
The number generated by reversing the digits."""

# Input the 3-digit number
num = int(input())

# Extract the digits
digit1 = num // 100
digit2 = (num % 100) // 10
digit3 = num % 10

# Reverse the digits and form the reversed number
reversed_num = digit3 * 100 + digit2 * 10 + digit1

# Print the reversed number
print(reversed_num)
